package javapractice;

public class TestException {
	public static void main(String[] args){
		int x = 7;
		int y = 0;
		int a[] = {1,2,3,4,5,6};
    // DriverManager.getConnection(" ");
	    try{
	    	int r = x/y;
	    	System.out.println("result = "+r);
	        System.out.println("value = "+a[7]);	
	    }
	    catch(ArithmeticException e){
	    	e.printStackTrace();
	    }
	    catch(ArrayIndexOutOfBoundsException e){
	    	e.printStackTrace();
	    }
	    System.out.println("success");
	}

}
